filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: true
build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run
    environment:
        php:
            version:                "8.2"
            ini:
                memory_limit:       "-1"
